name = "Metrology"
version = "0.1.0"
defaultTargets = ["metrology"]

[leanOptions]
pp.unicode.fun = true
# relaxedAutoImplicit = false
# weak.linter.mathlibStandardSet = true
# maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[require]]
name = "iris"
git = "https://github.com/leanprover-community/iris-lean.git"
rev = "master"

[[lean_lib]]
name = "Metrology"

[[lean_exe]]
name = "metrology"
root = "Main"

[[lean_lib]]
name = "ProbLangTest"
roots = ["Metrology.ProbLang.Test"]
