name = "metrology"
defaultTargets = ["Metrology"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.32.2"

[[require]]
name = "cslib"
git = "https://github.com/leanprover/cslib"
rev = "v4.32.2"

[[require]]
name = "iris"
git = "https://github.com/leanprover-community/iris-lean.git"
subDir = "Iris"

[[lean_lib]]
name = "Metrology"
