-- Definition head_step (e1 : expr) (σ1 : state) : distr (expr * state) :=
--   match e1 with
--   | Rec f x e =>
--       dret (Val $ RecV f x e, σ1)
--   | Pair (Val v1) (Val v2) =>
--       dret (Val $ PairV v1 v2, σ1)
--   | InjL (Val v) =>
--       dret (Val $ InjLV v, σ1)
--   | InjR (Val v) =>
--       dret (Val $ InjRV v, σ1)
--   | App (Val (RecV f x e1)) (Val v2) =>
--       dret (subst' x v2 (subst' f (RecV f x e1) e1) , σ1)
--   | UnOp op (Val v) =>
--       match un_op_eval op v with
--         | Some w => dret (Val w, σ1)
--         | _ => dzero
--       end
--   | BinOp op (Val v1) (Val v2) =>
--       match bin_op_eval op v1 v2 with
--         | Some w => dret (Val w, σ1)
--         | _ => dzero
--       end
--   | If (Val (LitV (LitBool true))) e1 e2  =>
--       dret (e1 , σ1)
--   | If (Val (LitV (LitBool false))) e1 e2 =>
--       dret (e2 , σ1)
--   | Fst (Val (PairV v1 v2)) =>
--       dret (Val v1, σ1)
--   | Snd (Val (PairV v1 v2)) =>
--       dret (Val v2, σ1)
--   | Case (Val (InjLV v)) e1 e2 =>
--       dret (App e1 (Val v), σ1)
--   | Case (Val (InjRV v)) e1 e2 =>
--       dret (App e2 (Val v), σ1)
--   | AllocN (Val (LitV (LitInt N))) (Val v) =>
--       let ℓ := fresh_loc σ1.(heap) in
--       if bool_decide (0 < Z.to_nat N)%nat
--         then dret (Val $ LitV $ LitLoc ℓ, state_upd_heap_N ℓ (Z.to_nat N) v σ1)
--         else dzero
--   | Load (Val (LitV (LitLoc l))) =>
--       match σ1.(heap) !! l with
--         | Some v => dret (Val v, σ1)
--         | None => dzero
--       end
--   | Store (Val (LitV (LitLoc l))) (Val w) =>
--       match σ1.(heap) !! l with
--         | Some v => dret (Val $ LitV LitUnit, state_upd_heap <[l:=w]> σ1)
--         | None => dzero
--       end
--   (* Since our language only has integers, we use Z.to_nat, which maps positive
--      integers to the corresponding nat, and the rest to 0. We sample from
--      [dunifP N = dunif (1 + N)] to avoid the case [dunif 0 = dzero]. *)
--   (* Uniform sampling from [0, 1 , ..., N] *)
--   | Rand (Val (LitV (LitInt N))) (Val (LitV LitUnit)) =>
--       dmap (λ n : fin _, (Val $ LitV $ LitInt n, σ1)) (dunifP (Z.to_nat N))
--   | AllocTape (Val (LitV (LitInt z))) =>
--       let ι := fresh_loc σ1.(tapes) in
--       dret (Val $ LitV $ LitLbl ι, state_upd_tapes <[ι := (Z.to_nat z; []) ]> σ1)
--   (* Labelled sampling, conditional on tape contents *)
--   | Rand (Val (LitV (LitInt N))) (Val (LitV (LitLbl l))) =>
--       match σ1.(tapes) !! l with
--       | Some (M; ns) =>
--           if bool_decide (M = Z.to_nat N) then
--             match ns  with
--             | n :: ns =>
--                 (* the tape is non-empty so we consume the first number *)
--                 dret (Val $ LitV $ LitInt $ fin_to_nat n, state_upd_tapes <[l:=(M; ns)]> σ1)
--             | [] =>
--                 (* the tape is allocated but empty, so we sample from [0, 1, ..., M] uniformly *)
--                 dmap (λ n : fin _, (Val $ LitV $ LitInt n, σ1)) (dunifP M)
--             end
--           else
--             (* bound did not match the bound of the tape *)
--             dmap (λ n : fin _, (Val $ LitV $ LitInt n, σ1)) (dunifP (Z.to_nat N))
--       | None => dzero
--       end
--   | _ => dzero
--   end.

-- Definition state_step (σ1 : state) (α : loc) : distr state :=
--   if bool_decide (α ∈ dom σ1.(tapes)) then
--     let: (N; ns) := (σ1.(tapes) !!! α) in
--     dmap (λ n, state_upd_tapes (<[α := (N; ns ++ [n])]>) σ1) (dunifP N)
--   else dzero.

-- Lemma state_step_unfold σ α N ns:
--   tapes σ !! α = Some (N; ns) ->
--   state_step σ α = dmap (λ n, state_upd_tapes (<[α := (N; ns ++ [n])]>) σ) (dunifP N).
-- Proof.
--   intros H.
--   rewrite /state_step.
--   rewrite bool_decide_eq_true_2; last first.
--   { by apply elem_of_dom. }
--   by rewrite (lookup_total_correct (tapes σ) α (N; ns)); last done.
-- Qed.

-- Global Instance fill_item_inj Ki : Inj (=) (=) (fill_item Ki).
-- Proof. induction Ki; intros ???; simplify_eq/=; auto with f_equal. Qed.

-- Lemma fill_item_val Ki e :
--   is_Some (to_val (fill_item Ki e)) → is_Some (to_val e).
-- Proof. intros [v ?]. induction Ki; simplify_option_eq; eauto. Qed.

-- Lemma val_head_stuck e σ ρ :
--   head_step e σ ρ > 0 → to_val e = None.
-- Proof. destruct ρ, e; [|done..]. rewrite /pmf /=. lra. Qed.
-- Lemma head_ctx_step_val Ki e σ ρ :
--   head_step (fill_item Ki e) σ ρ > 0 → is_Some (to_val e).
-- Proof.
--   destruct ρ, Ki ;
--     rewrite /pmf/= ;
--     repeat case_match; clear -H ; inversion H; intros ; (lra || done).
-- Qed.

-- Inductive head_step_rel : expr → state → expr → state → Prop :=
-- | RecS f x e σ :
--   head_step_rel (Rec f x e) σ (Val $ RecV f x e) σ
-- | PairS v1 v2 σ :
--   head_step_rel (Pair (Val v1) (Val v2)) σ (Val $ PairV v1 v2) σ
-- | InjLS v σ :
--   head_step_rel (InjL $ Val v) σ (Val $ InjLV v) σ
-- | InjRS v σ :
--   head_step_rel (InjR $ Val v) σ (Val $ InjRV v) σ
-- | BetaS f x e1 v2 e' σ :
--   e' = subst' x v2 (subst' f (RecV f x e1) e1) →
--   head_step_rel (App (Val $ RecV f x e1) (Val v2)) σ e' σ
-- | UnOpS op v v' σ :
--   un_op_eval op v = Some v' →
--   head_step_rel (UnOp op (Val v)) σ (Val v') σ
-- | BinOpS op v1 v2 v' σ :
--   bin_op_eval op v1 v2 = Some v' →
--   head_step_rel (BinOp op (Val v1) (Val v2)) σ (Val v') σ
-- | IfTrueS e1 e2 σ :
--   head_step_rel (If (Val $ LitV $ LitBool true) e1 e2) σ e1 σ
-- | IfFalseS e1 e2 σ :
--   head_step_rel (If (Val $ LitV $ LitBool false) e1 e2) σ e2 σ
-- | FstS v1 v2 σ :
--   head_step_rel (Fst (Val $ PairV v1 v2)) σ (Val v1) σ
-- | SndS v1 v2 σ :
--   head_step_rel (Snd (Val $ PairV v1 v2)) σ (Val v2) σ
-- | CaseLS v e1 e2 σ :
--   head_step_rel (Case (Val $ InjLV v) e1 e2) σ (App e1 (Val v)) σ
-- | CaseRS v e1 e2 σ :
--   head_step_rel (Case (Val $ InjRV v) e1 e2) σ (App e2 (Val v)) σ
-- | AllocNS z N v σ l :
--   l = fresh_loc σ.(heap) →
--   N = Z.to_nat z →
--   (0 < N)%nat ->
--   head_step_rel (AllocN (Val (LitV (LitInt z))) (Val v)) σ
--     (Val $ LitV $ LitLoc l) (state_upd_heap_N l N v σ)
-- | LoadS l v σ :
--   σ.(heap) !! l = Some v →
--   head_step_rel (Load (Val $ LitV $ LitLoc l)) σ (of_val v) σ
-- | StoreS l v w σ :
--   σ.(heap) !! l = Some v →
--   head_step_rel (Store (Val $ LitV $ LitLoc l) (Val w)) σ
--     (Val $ LitV LitUnit) (state_upd_heap <[l:=w]> σ)
-- | RandNoTapeS z N (n : fin (S N)) σ :
--   N = Z.to_nat z →
--   head_step_rel (Rand (Val $ LitV $ LitInt z) (Val $ LitV LitUnit)) σ (Val $ LitV $ LitInt n) σ
-- | AllocTapeS z N σ l :
--   l = fresh_loc σ.(tapes) →
--   N = Z.to_nat z →
--   head_step_rel (AllocTape (Val (LitV (LitInt z)))) σ
--     (Val $ LitV $ LitLbl l) (state_upd_tapes <[l := (N; []) : tape]> σ)
-- | RandTapeS l z N n ns σ :
--   N = Z.to_nat z →
--   σ.(tapes) !! l = Some ((N; n :: ns) : tape)  →
--   head_step_rel (Rand (Val (LitV (LitInt z))) (Val (LitV (LitLbl l)))) σ
--     (Val $ LitV $ LitInt $ n) (state_upd_tapes <[l := (N; ns) : tape]> σ)
-- | RandTapeEmptyS l z N (n : fin (S N)) σ :
--   N = Z.to_nat z →
--   σ.(tapes) !! l = Some ((N; []) : tape) →
--   head_step_rel (Rand (Val (LitV (LitInt z))) (Val $ LitV $ LitLbl l)) σ (Val $ LitV $ LitInt n) σ
-- | RandTapeOtherS l z M N ms (n : fin (S N)) σ :
--   N = Z.to_nat z →
--   σ.(tapes) !! l = Some ((M; ms) : tape) →
--   N ≠ M →
--   head_step_rel (Rand (Val (LitV (LitInt z))) (Val $ LitV $ LitLbl l)) σ (Val $ LitV $ LitInt n) σ
--
-- | LaplaceS num den loc (z : Z) σ :
--   (0 < IZR num / IZR den) →
--   head_step_rel (Laplace (Val $ LitV $ LitInt num) (Val $ LitV $ LitInt den) (Val $ LitV $ LitInt loc)) σ (Val $ LitV $ LitInt z) σ
--
-- | LaplaceS0 num den loc (z : Z) σ :
--   (not (0 < IZR num / IZR den)) →
--   head_step_rel (Laplace (Val $ LitV $ LitInt num) (Val $ LitV $ LitInt den) (Val $ LitV $ LitInt loc)) σ (Val $ LitV $ LitInt loc) σ
--
-- | TickS σ z :
--   head_step_rel (Tick $ Val $ LitV $ LitInt z) σ (Val $ LitV $ LitUnit) σ.

-- Inductive state_step_rel : state → loc → state → Prop :=
-- | AddTapeS α N (n : fin (S N)) ns σ :
--   α ∈ dom σ.(tapes) →
--   σ.(tapes) !!! α = ((N; ns) : tape) →
--   state_step_rel σ α (state_upd_tapes <[α := (N; ns ++ [n]) : tape]> σ).

-- Lemma head_step_support_equiv_rel e1 e2 σ1 σ2 :
--   head_step e1 σ1 (e2, σ2) > 0 ↔ head_step_rel e1 σ1 e2 σ2.
-- Proof.
--   split.
--   - intros ?. destruct e1; inv_head_step ; eauto with head_step.
--   - inversion 1; simplify_map_eq/= ; try case_bool_decide ; try case_decide ; simplify_eq; solve_distr; try done.
-- Qed.

-- Lemma state_step_support_equiv_rel σ1 α σ2 :
--   state_step σ1 α σ2 > 0 ↔ state_step_rel σ1 α σ2.
-- Proof.
--   rewrite /state_step. split.
--   - case_bool_decide; [|intros; inv_distr].
--     case_match. intros ?. inv_distr.
--     econstructor; eauto with lia.
--   - inversion_clear 1.
--     rewrite bool_decide_eq_true_2 // H1. solve_distr.
-- Qed.
--
-- Lemma state_step_head_step_not_stuck e σ σ' α :
--   state_step σ α σ' > 0 → (∃ ρ, head_step e σ ρ > 0) ↔ (∃ ρ', head_step e σ' ρ' > 0).
-- Proof.
--   rewrite state_step_support_equiv_rel.
--   inversion_clear 1.
--   split; intros [[e2 σ2] Hs].
--   (* TODO: the sub goals used to be solved by [simplify_map_eq]  *)
--   - destruct e; inv_head_step; try by (unshelve (eexists; solve_distr)).
--     + destruct (decide (α = l1)); simplify_eq.
--       * rewrite lookup_insert in H11. done.
--       * rewrite lookup_insert_ne // in H11. rewrite H11 in H7. done.
--     + destruct (decide (α = l1)); simplify_eq.
--       * rewrite lookup_insert in H11. done.
--       * rewrite lookup_insert_ne // in H11. rewrite H11 in H7. done.
--     + destruct (decide (α = l1)); simplify_eq.
--       * rewrite lookup_insert in H10. done.
--       * rewrite lookup_insert_ne // in H10. rewrite H10 in H7. done.
--   - destruct e; inv_head_step; try by (unshelve (eexists; solve_distr)).
--     + destruct (decide (α = l1)); simplify_eq.
--       * apply not_elem_of_dom_2 in H11. done.
--       * rewrite lookup_insert_ne // in H7. rewrite H11 in H7.  done.
--     + destruct (decide (α = l1)); simplify_eq.
--       * rewrite lookup_insert // in H7.
--         apply not_elem_of_dom_2 in H11. done.
--       * rewrite lookup_insert_ne // in H7. rewrite H11 in H7. done.
--     + destruct (decide (α = l1)); simplify_eq.
--       * rewrite lookup_insert // in H7.
--         apply not_elem_of_dom_2 in H10. done.
--       * rewrite lookup_insert_ne // in H7. rewrite H10 in H7. done.
-- Qed.

-- Lemma state_step_mass σ α :
--   α ∈ dom σ.(tapes) → SeriesC (state_step σ α) = 1.
-- Proof.
--   intros Hdom.
--   rewrite /state_step bool_decide_eq_true_2 //=.
--   case_match.
--   rewrite dmap_mass dunif_mass //.
-- Qed.

-- Lemma head_step_mass e σ :
--   (∃ ρ, head_step e σ ρ > 0) → SeriesC (head_step e σ) = 1.
-- Proof.
--   intros [[] Hs%head_step_support_equiv_rel].
--   inversion Hs;
--     repeat (simplify_map_eq/=; solve_distr_mass || (case_match ; try done) ;
--             try (case_bool_decide; done)).
-- Qed.

-- Lemma fill_item_no_val_inj Ki1 Ki2 e1 e2 :
--   to_val e1 = None → to_val e2 = None →
--   fill_item Ki1 e1 = fill_item Ki2 e2 → Ki1 = Ki2.
-- Proof. destruct Ki2, Ki1; naive_solver eauto with f_equal. Qed.

-- Fixpoint height (e : expr) : nat :=
--   match e with
--   | Val _ => 1
--   | Var _ => 1
--   | Rec _ _ e => 1 + height e
--   | App e1 e2 => 1 + height e1 + height e2
--   | UnOp _ e => 1 + height e
--   | BinOp _ e1 e2 => 1 + height e1 + height e2
--   | If e0 e1 e2 => 1 + height e0 + height e1 + height e2
--   | Pair e1 e2 => 1 + height e1 + height e2
--   | Fst e => 1 + height e
--   | Snd e => 1 + height e
--   | InjL e => 1 + height e
--   | InjR e => 1 + height e
--   | Case e0 e1 e2 => 1 + height e0 + height e1 + height e2
--   | AllocN e1 e2 => 1 + height e1 + height e2
--   | Load e => 1 + height e
--   | Store e1 e2 => 1 + height e1 + height e2
--   | AllocTape e => 1 + height e
--   | Rand e1 e2 => 1 + height e1 + height e2
--   | Laplace e1 e2 e3 => 1 + height e1 + height e2 + height e3
--   | Tick e => 1 + height e
--   end.
--
-- Definition expr_ord (e1 e2 : expr) : Prop := (height e1 < height e2)%nat.
--
-- Lemma expr_ord_wf' h e : (height e ≤ h)%nat → Acc expr_ord e.
-- Proof.
--   rewrite /expr_ord. revert e; induction h.
--   { destruct e; simpl; lia. }
--   intros []; simpl;
--     constructor; simpl; intros []; eauto with lia.
-- Defined.
--
-- Lemma expr_ord_wf : well_founded expr_ord.
-- Proof. red; intro; eapply expr_ord_wf'; eauto. Defined.
--
-- Lemma decomp_expr_ord Ki e e' : decomp_item e = Some (Ki, e') → expr_ord e' e.
-- Proof.
--   rewrite /expr_ord /decomp_item.
--   destruct Ki ; repeat destruct_match ; intros [=] ; subst ; cbn ; lia.
-- Qed.
--
-- Lemma decomp_fill_item Ki e :
--   to_val e = None → decomp_item (fill_item Ki e) = Some (Ki, e).
-- Proof. destruct Ki ; simpl ; by repeat destruct_match. Qed.

-- Lemma decomp_fill_item_2 e e' Ki :
--   decomp_item e = Some (Ki, e') → fill_item Ki e' = e ∧ to_val e' = None.
-- Proof.
--   rewrite /decomp_item ;
--     destruct e ; try done ;
--     destruct Ki ; cbn ; repeat destruct_match ; intros [=] ; subst ; auto.
-- Qed.

-- Definition get_active (σ : state) : list loc := elements (dom σ.(tapes)).

-- Lemma state_step_get_active_mass σ α :
--   α ∈ get_active σ → SeriesC (state_step σ α) = 1.
-- Proof. rewrite elem_of_elements. apply state_step_mass. Qed.

-- Lemma state_steps_mass σ αs :
--   αs ⊆ get_active σ →
--   SeriesC (foldlM state_step σ αs) = 1.
-- Proof.
--   induction αs as [|α αs IH] in σ |-* ; intros Hact.
--   { rewrite /= dret_mass //. }
--   rewrite foldlM_cons.
--   rewrite dbind_det //.
--   - apply state_step_get_active_mass. set_solver.
--   - intros σ' Hσ'. apply IH.
--     apply state_step_support_equiv_rel in Hσ'.
--     inversion Hσ'; simplify_eq.
--     intros α' ?. rewrite /get_active /=.
--     apply elem_of_elements, elem_of_dom.
--     destruct (decide (α = α')); subst.
--     + eexists. rewrite lookup_insert //.
--     + rewrite lookup_insert_ne //.
--       apply elem_of_dom. eapply elem_of_elements, Hact. by right.
-- Qed.






-- ------------- EctxiLanguage.v -------------

-- Notation ectx := (list (ectx_item Λ)).

--   Lemma fill_item_not_val K e : to_val e = None → to_val (fill_item K e) = None.
--   Proof. rewrite !eq_None_not_Some. eauto using fill_item_val. Qed.

--   Definition fill (K : ectx) (e : expr Λ) : expr Λ := foldl (flip fill_item) e K.

--   Lemma fill_app (K1 K2 : ectx) e : fill (K1 ++ K2) e = fill K2 (fill K1 e).
--   Proof. apply foldl_app. Qed.
--
--   Program Fixpoint decomp (e : expr Λ) {wf expr_ord e} : ectx * expr Λ :=
--     match decomp_item e with
--     | Some (Ki, e') => let '(K, e'') := decomp e' in (K ++ [Ki], e'')
--     | None => ([], e)
--     end.
--   Solve Obligations with eauto using decomp_ord, expr_ord_wf.
--
--   Lemma decomp_unfold e :
--     decomp e =
--       match decomp_item e with
--       | Some (Ki, e') => let '(K, e'') := decomp e' in (K ++ [Ki], e'')
--       | None => ([], e)
--       end.
--   Proof.
--     rewrite /decomp WfExtensionality.fix_sub_eq_ext /= -/decomp.
--     repeat case_match; try done.
--   Qed.
--
--   Lemma decomp_inv_nil e e' :
--     decomp e = ([], e') → decomp_item e = None ∧ e = e'.
--   Proof.
--     rewrite decomp_unfold.
--     destruct (decomp_item e) as [[Ki e'']|] eqn:Heq; [|by intros [=]].
--     destruct (decomp e''). intros [= Hl He].
--     assert (l = []) as ->.
--     { destruct l; inversion Hl. }
--     inversion Hl.
--   Qed.
--
--   Lemma decomp_inv_cons Ki K e e'' :
--     decomp e = (K ++ [Ki], e'') → ∃ e', decomp_item e = Some (Ki, e') ∧ decomp e' = (K, e'').
--   Proof.
--     rewrite decomp_unfold.
--     destruct (decomp_item e) as [[Ki' e']|] eqn:Heq'.
--     2 : { intros [=]. by destruct K. }
--     destruct (decomp e') as [K' e'''] eqn:Heq.
--     intros [= [<- <-]%list_snoc_singleton_inv ->].
--     eauto.
--   Qed.

--     assert (fill_val : ∀ K e, is_Some (to_val (fill K e)) → is_Some (to_val e)).
--     { intros K. induction K as [|Ki K IH]=> e //=. by intros ?%IH%fill_item_val. }

--     assert (fill_not_val : ∀ K e, to_val e = None → to_val (fill K e) = None).
--     { intros K e. rewrite !eq_None_not_Some. eauto. }


-- empty_ectxt := []
-- comp_ectxt := flip (++)

-- Lemma fill_comp : ∀ (K1 K2 : ectx) e, fill K1 (fill K2 e) = fill (flip app K1 K2) e
--     - intros K1 K2 e. by rewrite /fill /= foldl_app.

-- Lemma fill_inj : ∀ K : ectx, Inj eq eq (fill K)
--     - intros K; induction K as [|Ki K IH]; rewrite /Inj; naive_solver.

-- Lemma decomp_fill  : ∀ (K : ectx) e e', decomp e = (K, e') → fill K e' = e
--     - induction K as [|Ki K] using rev_ind; intros e e'.
--       { intros [? ->]%decomp_inv_nil=>//. }
--       intros (e'' & Hrei & Hre)%decomp_inv_cons.
--       rewrite fill_app /= (IHK e'') //.
--       by apply decomp_fill_item_2.


-- Lemma decomp_val_empty : ∀ (K : ectx) e e', decomp e = (K, e') → is_Some (to_val e') → K = []
--     - intros K. induction K as [|Ki K] using rev_ind; [done|].
--       intros ?? (e'' & Hrei & Hre)%decomp_inv_cons Hv.
--       specialize (IHK _ _ Hre Hv). simplify_eq.
--       apply decomp_inv_nil in Hre as [? ?]; simplify_eq.
--       by apply decomp_fill_item_2 in Hrei as [_ ?%eq_None_not_Some].

-- Lemma decomp_fill_comp  : ∀ e e' (K K' : ectx), to_val e = None → decomp e = (K', e') → decomp (fill K e) = (flip app K K', e')
--     - intros e e' K K'. revert K' e e'.
--       induction K as [|Ki K] using rev_ind.
--       { intros ??? =>/=. rewrite app_nil_r //. }
--       intros K' e e' Hval Hre. rewrite fill_app /=.
--       rewrite decomp_unfold.
--       rewrite decomp_fill_item; [|auto using fill_item_not_val].
--       rewrite (IHK K' _ e') //=.
--       rewrite !app_assoc //.

-- Lemma step_by_val :
--   ∀ (K' K_redex : ectx) (e1' e1_redex : expr Λ) (σ1 : state Λ) (ρ : expr Λ * state Λ),
--     fill K' e1' = fill K_redex e1_redex
--     → to_val e1' = None → head_step e1_redex σ1 ρ > 0 → ∃ K'' : ectx, K_redex = flip app K' K''
-- --     - intros K K' e1 e1' σ1 [e2 σ2] Hfill Hred Hstep; revert K' Hfill.
--       induction K as [|Ki K IH] using rev_ind=> /= K' Hfill; eauto using app_nil_r.
--       destruct K' as [|Ki' K' _] using @rev_ind; simplify_eq/=.
--       { rewrite fill_app in Hstep. apply head_ctx_step_val in Hstep.
--         apply fill_val in Hstep. by apply not_eq_None_Some in Hstep. }
--       rewrite !fill_app /= in Hfill.
--       assert (Ki = Ki') as ->.
--       { eapply fill_item_no_val_inj, Hfill; eauto using val_head_stuck.
--         apply fill_not_val. revert Hstep. apply ectxi_language_mixin. }
--       simplify_eq. destruct (IH K') as [K'' ->]; auto.
--       exists K''. by rewrite assoc.

-- Lemma head_ctx_step_val : ∀ (K : ectx) e (σ1 : state Λ) (ρ : expr Λ * state Λ), head_step (fill K e) σ1 ρ > 0 → is_Some (to_val e) ∨ K = []
--     - intros K e1 σ1 [e2 σ2].
--       destruct K as [|Ki K _] using rev_ind; simpl; first by auto.
--       rewrite fill_app /=.
--       intros ?%head_ctx_step_val; eauto using fill_val.

--   Lemma fill_not_val K e : to_val e = None → to_val (fill K e) = None.
--   Proof. rewrite !eq_None_not_Some. eauto using fill_val. Qed.
--
--   Lemma ectxi_language_sub_redexes_are_values e :
--     (∀ Ki e', e = fill_item Ki e' → is_Some (to_val e')) →
--     sub_redexes_are_values e.
--   Proof.
--     intros Hsub K e' ->. destruct K as [|Ki K _] using @rev_ind=> //=.
--     intros []%eq_None_not_Some. eapply fill_val, Hsub. by rewrite /= fill_app.
--   Qed.
--
--   Global Instance ectxi_lang_ctx_item Ki : LanguageCtx (fill_item Ki).
--   Proof. change (LanguageCtx (fill [Ki])). apply _. Qed.




-- ------------- EctxLanguage.v -------------

--   Class head_reducible (e : expr Λ) (σ : state Λ) :=
--     head_reducible_step : ∃ ρ, head_step e σ ρ > 0.

--   Definition head_irreducible (e : expr Λ) (σ : state Λ) :=
--     ∀ ρ, head_step e σ ρ = 0.

--   Definition head_stuck (e : expr Λ) (σ : state Λ) :=
--     to_val e = None ∧ head_irreducible e σ.

--   Definition sub_redexes_are_values (e : expr Λ) :=
--     ∀ K e', e = fill K e' → to_val e' = None → K = empty_ectx.
--
--   Definition fill_lift (K : ectx Λ) : (expr Λ * state Λ) → (expr Λ * state Λ) :=
--     λ '(e, σ), (fill K e, σ).
--
--   Lemma fill_lift_comp (K1 K2 : ectx Λ) :
--     fill_lift (comp_ectx K1 K2) = fill_lift K1 ∘ fill_lift K2.
--   Proof.
--     extensionality ρ. destruct ρ.
--     rewrite /fill_lift -fill_comp //=.
--   Qed.
--
--   Lemma fill_lift_empty :
--     fill_lift empty_ectx = (λ ρ, ρ).
--   Proof.
--     extensionality ρ. destruct ρ.
--     rewrite /fill_lift fill_empty //.
--   Qed.
--
--   Instance inj_fill (K : ectx Λ) : Inj eq eq (fill_lift K).
--   Proof. intros [] [] [=<-%(inj _) ->]=>//. Qed.
--
--   Definition prim_step (e1 : expr Λ) (σ1 : state Λ) : distr (expr Λ * state Λ) :=
--     let '(K, e1') := decomp e1 in
--     dmap (fill_lift K) (head_step e1' σ1).
--
--   Lemma fill_not_val K e : to_val e = None → to_val (fill K e) = None.
--   Proof. rewrite !eq_None_not_Some. eauto using fill_val. Qed.




-- Lemma val_stuck  : ∀ e (σ : state Λ) (ρ : expr Λ * state Λ), prim_step e σ ρ > 0 → to_val e = None
--     - intros e1 σ1 [e2 σ2] =>/=. rewrite /prim_step.
--       destruct (decomp e1) as [K e1'] eqn:Heq.
--       intros [[e2' σ2'] [_ Hs]]%dmap_pos.
--       rewrite -(decomp_fill _ _ _ Heq).
--       eapply fill_not_val.
--       by eapply val_head_stuck.

-- Lemma state_step_not_stuck :
--   ∀ e (σ σ' : state Λ) (α : state_idx Λ),
--     state_step σ α σ' > 0
--     → (∃ ρ : expr Λ * state Λ, prim_step e σ ρ > 0) ↔ ∃ ρ' : expr Λ * state Λ, prim_step e σ' ρ' > 0
--     - intros e1 σ1 σ1' α. rewrite /prim_step.
--       destruct (decomp e1) as [K e1'] eqn:Heq.
--       intros Hs. split.
--       + intros [[e2 σ2] [[e2' σ2'] [_ Hh]]%dmap_pos].
--         assert (∃ ρ, head_step e1' σ1' ρ > 0) as [[e2'' σ2''] Hs'].
--         { erewrite <-state_step_head_not_stuck; [|done]. eauto. }
--         eexists (fill K e2'', σ2'').
--         eapply dmap_pos.
--         eexists (_, _). eauto.
--       + intros [[e2 σ2] [[e2' σ2'] [_ Hh]]%dmap_pos].
--         assert (∃ ρ, head_step e1' σ1 ρ > 0) as [[e2'' σ2''] Hs'].
--         { erewrite state_step_head_not_stuck; [|done]. eauto. }
--         eexists (fill K e2'', σ2'').
--         eapply dmap_pos.
--         eexists (_, _); eauto.

-- Lemma prim_step_mass : ∀ e (σ : state Λ), (∃ ρ : expr Λ * state Λ, prim_step e σ ρ > 0) → SeriesC (prim_step e σ) = 1
--     - intros e σ [[e' σ'] Hs]. revert Hs. rewrite /prim_step.
--       destruct (decomp e) as [K e1'] eqn:Heq.
--       intros [[e2' σ2'] [? Hs]]%dmap_pos.
--       assert (SeriesC (head_step e1' σ) = 1) as Hsum; [eauto using head_step_mass|].
--       rewrite dmap_mass //.
--   Qed.


--   Definition head_atomic (a : atomicity) (e : expr Λ) : Prop :=
--     ∀ σ e' σ',
--       head_step e σ (e', σ') > 0 →
--       if a is WeaklyAtomic then irreducible (e', σ') else is_Some (to_val e').
--
--   (** * Some lemmas about this language *)
--   Lemma not_head_reducible e σ : ¬head_reducible e σ ↔ head_irreducible e σ.
--   Proof.
--     unfold head_reducible, head_irreducible. split.
--     - intros Hnot ρ.
--       assert (¬ head_step e σ ρ > 0) as H%Rnot_gt_ge; eauto.
--       pose proof (pmf_pos (head_step e σ) ρ). lra.
--     - intros Hall [ρ ?]. specialize (Hall ρ). lra.
--   Qed.
--
--   (** The decomposition into head redex and context is unique.
--       In all sensible instances, [comp_ectx K' empty_ectx] will be the same as
--       [K'], so the conclusion is [K = K' ∧ e = e'], but we do not require a law
--       to actually prove that so we cannot use that fact here. *)
--   Lemma head_redex_unique K K' e e' σ :
--     fill K e = fill K' e' →
--     head_reducible e σ →
--     head_reducible e' σ →
--     K = comp_ectx K' empty_ectx ∧ e = e'.
--   Proof.
--     intros Heq [[e2 σ2] Hred] [[e2' σ2'] Hred'].
--     edestruct (step_by_val K' K e' e) as [K'' HK];
--       [by eauto using val_head_stuck..|].
--     subst K. move: Heq. rewrite -fill_comp. intros <-%(inj (fill _)).
--     destruct (head_ctx_step_val _ _ _ _ Hred') as [[]%not_eq_None_Some|HK''].
--     { by eapply val_head_stuck. }
--     subst K''. rewrite fill_empty. done.
--   Qed.
--
--   Lemma fill_prim_step_dbind K e1 σ1 :
--     to_val e1 = None →
--     prim_step (fill K e1) σ1 = dmap (fill_lift K) (prim_step e1 σ1).
--   Proof.
--     intros Hval. rewrite /prim_step.
--     destruct (decomp e1) as [K1 e1'] eqn:Heq.
--     destruct (decomp (fill _ e1)) as [K1' e1''] eqn:Heq'.
--     apply (decomp_fill_comp K) in Heq; [|done].
--     rewrite Heq in Heq'; simplify_eq.
--     rewrite dmap_comp.
--     apply dmap_eq; [|done].
--     intros [] ? =>/=.
--     f_equal. rewrite -fill_comp //.
--   Qed.
--
--   Lemma fill_prim_step K e1 σ1 e2 σ2 :
--     to_val e1 = None →
--     prim_step e1 σ1 (e2, σ2) = prim_step (fill K e1) σ1 (fill K e2, σ2).
--   Proof.
--     intros Hval. rewrite /prim_step.
--     destruct (decomp e1) as [K1 e1'] eqn:Heq.
--     destruct (decomp (fill _ e1)) as [K1' e1''] eqn:Heq'.
--     apply (decomp_fill_comp K) in Heq; [|done].
--     rewrite Heq in Heq'; simplify_eq.
--     rewrite fill_lift_comp -/fill_lift.
--     rewrite -dmap_comp.
--     replace (fill K e2, σ2) with (fill_lift K (e2, σ2)); [|done].
--     rewrite (dmap_elem_eq (dmap _ _) (e2, σ2)) //.
--   Qed.
--
--   Lemma head_prim_step_pmf_eq e1 σ1 ρ :
--     head_reducible e1 σ1 →
--     prim_step e1 σ1 ρ = head_step e1 σ1 ρ.
--   Proof.
--     intros Hred.
--     rewrite /= /prim_step.
--     destruct (decomp e1) as [K e1'] eqn:Heq.
--     edestruct (decomp_fill _ _ _ Heq).
--     destruct Hred as [ρ' Hs].
--     destruct (head_ctx_step_val _ _ _ _ Hs) as [| ->].
--     - assert (K = empty_ectx) as -> by eauto using decomp_val_empty.
--       rewrite fill_lift_empty fill_empty dmap_id //=.
--     - rewrite fill_lift_empty fill_empty dmap_id //=.
--   Qed.
--
--   Lemma head_prim_step_eq e1 σ1 :
--     head_reducible e1 σ1 →
--     prim_step e1 σ1 = head_step e1 σ1.
--   Proof. intros ?. apply distr_ext=>?. by eapply head_prim_step_pmf_eq. Qed.
--
--   Lemma head_prim_step e1 σ1 ρ :
--     head_step e1 σ1 ρ > 0 → prim_step e1 σ1 ρ > 0.
--   Proof. intros ?. erewrite head_prim_step_eq; [done|]. eexists; eauto. Qed.
--
--   Lemma prim_step_iff e1 e2 σ1 σ2 :
--     prim_step e1 σ1 (e2, σ2) > 0 ↔
--     ∃ K e1' e2',
--       fill K e1' = e1 ∧
--       fill K e2' = e2 ∧
--       head_step e1' σ1 (e2', σ2) > 0.
--   Proof.
--     split.
--     - rewrite /= /prim_step. intros Hs.
--       destruct (decomp e1) as [K e1'] eqn:Heq.
--       edestruct (decomp_fill _ _ _ Heq).
--       eapply dmap_pos in Hs as [[] [[=] ?]].
--       simplify_eq. do 3 eexists; eauto.
--     - intros (K & e1' & e2' & Hfill1 & Hfill2 & Hs). simplify_eq.
--       rewrite -fill_prim_step //; [by apply head_prim_step|].
--       by eapply val_head_stuck.
--   Qed.
--
--   Lemma head_step_not_stuck e σ ρ : head_step e σ ρ > 0 → not_stuck (e, σ).
--   Proof.
--     rewrite /not_stuck /reducible /=. intros Hs. right.
--     eexists ρ. by apply head_prim_step.
--   Qed.
--
--   Lemma fill_reducible K e σ : reducible (e, σ) → reducible (fill K e, σ).
--   Proof.
--     rewrite /reducible /=. intros [[e2 σ2] (K' & e1' & e2' & <- & <- & Hs)%prim_step_iff].
--     exists (fill (comp_ectx K K') e2', σ2).
--     eapply prim_step_iff. do 3 eexists. rewrite !fill_comp //.
--   Qed.

--   Lemma head_prim_reducible e σ : head_reducible e σ → reducible (e, σ).
--   Proof. intros [ρ Hstep]. exists ρ. by apply head_prim_step. Qed.

--   Lemma head_prim_fill_reducible e K σ :
--     head_reducible e σ → reducible (fill K e, σ).
--   Proof. intro. by apply fill_reducible, head_prim_reducible. Qed.

--   Lemma state_step_head_reducible e σ σ' α :
--     state_step σ α σ' > 0 → head_reducible e σ ↔ head_reducible e σ'.
--   Proof. eapply state_step_head_not_stuck. Qed.
--
--   Lemma head_prim_irreducible e σ : irreducible (e, σ) → head_irreducible e σ.
--   Proof.
--     rewrite -not_reducible -not_head_reducible. eauto using head_prim_reducible.
--   Qed.
--
--   Lemma prim_head_reducible e σ :
--     reducible (e, σ) → sub_redexes_are_values e → head_reducible e σ.
--   Proof.
--     rewrite /reducible.
--     intros [[e2 σ2] (K & e1' & e2' & ? & ? & Hs)%prim_step_iff] Hsub.
--     simplify_eq=>/=; simpl in *.
--     assert (K = empty_ectx) as -> by eauto 10 using val_head_stuck.
--     simplify_eq. rewrite fill_empty. eexists; eauto.
--   Qed.
--   Lemma prim_head_irreducible e σ :
--     head_irreducible e σ → sub_redexes_are_values e → irreducible (e, σ).
--   Proof.
--     rewrite -not_reducible -not_head_reducible. eauto using prim_head_reducible.
--   Qed.
--
--   Lemma head_stuck_stuck e σ :
--     head_stuck e σ → sub_redexes_are_values e → stuck (e, σ).
--   Proof.
--     intros [] ?. split; [by eapply to_final_None_2|].
--     by apply prim_head_irreducible.
--   Qed.
--
--   Lemma ectx_language_atomic a e :
--     head_atomic a e → sub_redexes_are_values e → Atomic a e.
--   Proof.
--     intros Hatomic Hsub σ e' σ' (K & e1' & e2' & <- & <- & Hs)%prim_step_iff.
--     assert (K = empty_ectx) as -> by eauto 10 using val_head_stuck.
--     rewrite fill_empty in Hatomic.
--     eapply Hatomic. rewrite fill_empty. eauto.
--   Qed.
--
--   Lemma head_reducible_prim_step_ctx K e1 σ1 e2 σ2:
--     head_reducible e1 σ1 →
--     prim_step (fill K e1) σ1 (e2, σ2) > 0 →
--     ∃ e2', e2 = fill K e2' ∧ head_step e1 σ1 (e2', σ2) > 0.
--   Proof.
--     intros [[e2'' σ2''] HhstepK] (K' & e1' & e2' & HKe1 & HKe2 & Hs)%prim_step_iff.
--     symmetry in HKe1.
--     edestruct (step_by_val K) as [K'' HK]; eauto using val_head_stuck; simplify_eq/=.
--     rewrite -fill_comp in HKe1; simplify_eq.
--     exists (fill K'' e2'). rewrite fill_comp. split; [done|].
--     destruct (head_ctx_step_val _ _ _ _ HhstepK) as [[]%not_eq_None_Some|HK''].
--     { by eapply val_head_stuck. }
--     subst. rewrite !fill_empty //.
--   Qed.
--
--   Lemma head_reducible_prim_step e1 σ1 ρ :
--     head_reducible e1 σ1 →
--     prim_step e1 σ1 ρ > 0 → head_step e1 σ1 ρ > 0.
--   Proof.
--     intros. destruct ρ.
--     edestruct (head_reducible_prim_step_ctx empty_ectx) as (?&?&?);
--       rewrite ?fill_empty; eauto.
--     by simplify_eq; rewrite fill_empty.
--   Qed.
--
--   (** Stronger lemma of prim_step_iff*)
--   Lemma prim_step_iff' e1 σ1:
--     (∃ x, prim_step e1 σ1 x > 0) ->
--     ∃ K e1', fill K e1' = e1 /\
--              (∃ x, head_step e1' σ1 x > 0) /\
--              prim_step e1 σ1 =
--              dmap (fill_lift K) (head_step e1' σ1).
--   Proof.
--     intros [[] H].
--     rewrite prim_step_iff in H.
--     destruct H as (K&e1'&e2'&<-&<-&H).
--     eexists _, _.
--     split; first done.
--     split; first naive_solver.
--     rewrite fill_prim_step_dbind.
--     - erewrite head_prim_step_eq; first done.
--       by eexists _.
--     - by eapply val_head_stuck.
--   Qed.
--
--   Lemma not_head_reducible_dzero e σ :
--     head_irreducible e σ → head_step e σ = dzero.
--   Proof.
--     rewrite /reducible.
--     intros Hred%not_head_reducible. apply dzero_ext=> ρ.
--     destruct (Req_dec (head_step e σ ρ) 0); [done|].
--     exfalso. apply Hred.
--     exists ρ.
--     pose proof (pmf_le_1 (head_step e σ) ρ).
--     pose proof (pmf_pos (head_step e σ) ρ).
--     lra.
--   Qed.
--

--   Record pure_head_step (e1 e2 : expr Λ) := {
--     pure_head_step_safe σ1 : head_reducible e1 σ1;
--     pure_head_step_det σ1 : head_step e1 σ1 (e2, σ1) = 1;
--   }.
--
--   Lemma pure_head_step_pure_step e1 e2 : pure_head_step e1 e2 → pure_step e1 e2.
--   Proof.
--     intros [Hp1 Hp2]. split.
--     - intros σ. destruct (Hp1 σ) as ([e2' σ2] & ?).
--       eexists (e2', σ2). by apply head_prim_step.
--     - intros σ1. rewrite /= head_prim_step_eq //.
--   Qed.
--
--   Lemma pure_exec_fill K φ n e1 e2 :
--     PureExec φ n e1 e2 →
--     PureExec φ n (fill K e1) (fill K e2).
--   Proof. apply: pure_exec_ctx. Qed.

-- ------------- Language.v -------------

-- Definition cfg (Λ : language) := (expr Λ * state Λ)%type.

-- Definition fill_lift {Λ} (K : expr Λ → expr Λ) : (expr Λ * state Λ) → (expr Λ * state Λ) :=
--   λ '(e, σ), (K e, σ).
--
-- Global Instance inj_fill_lift {Λ : language} (K : expr Λ → expr Λ) :
--   Inj (=) (=) K →
--   Inj (=) (=) (fill_lift K).
-- Proof. by intros ? [] [] [=->%(inj _) ->]. Qed.

-- Definition lang_markov_mixin (Λ : language) :
--   MarkovMixin (λ (ρ : expr Λ * state Λ), prim_step ρ.1 ρ.2) (λ (ρ : expr Λ * state Λ), to_val ρ.1).
-- Proof.
--   constructor.
--   move=> [e σ] /= [v Hv] [e' σ'].
--   case (Rgt_dec (prim_step e σ (e', σ')) 0)
--     as [H | ?%pmf_eq_0_not_gt_0]; simplify_eq=>//=.
--   eapply mixin_val_stuck in H; [|eapply language_mixin].
--   simplify_eq.
-- Qed.
--
-- Inductive atomicity := StronglyAtomic | WeaklyAtomic.
--
--   Lemma strongly_atomic_atomic e a :
--     Atomic StronglyAtomic e → Atomic a e.
--   Proof.
--     unfold Atomic. destruct a; eauto.
--     intros ?????. eapply is_final_irreducible.
--     rewrite /is_final /to_final /=. eauto.
--   Qed.
--
--   Lemma fill_step e1 σ1 e2 σ2 `{!LanguageCtx K} :
--     prim_step e1 σ1 (e2, σ2) > 0 →
--     prim_step (K e1) σ1 (K e2, σ2) > 0.
--   Proof.
--     intros Hs.
--     rewrite fill_dmap; [|by eapply val_stuck].
--     apply dbind_pos. eexists (_,_). split; [|done].
--     rewrite dret_1_1 //. lra.
--   Qed.
--
--   Lemma fill_step_inv e1' σ1 e2 σ2 `{!LanguageCtx K} :
--     to_val e1' = None → prim_step (K e1') σ1 (e2, σ2) > 0 →
--     ∃ e2', e2 = K e2' ∧ prim_step e1' σ1 (e2', σ2) > 0.
--   Proof.
--     intros Hv. rewrite fill_dmap //.
--     intros ([e1 σ1'] & [=]%dret_pos & Hstep)%dbind_pos.
--     subst. eauto.
--   Qed.
--
--   Lemma fill_step_prob e1 σ1 e2 σ2 `{!LanguageCtx K} :
--     to_val e1 = None →
--     prim_step e1 σ1 (e2, σ2) = prim_step (K e1) σ1 (K e2, σ2).
--   Proof.
--     intros Hv. rewrite fill_dmap //.
--     by erewrite (dmap_elem_eq _ (e2, σ2) _ (λ '(e0, σ0), (K e0, σ0))).
--   Qed.
--
--   Lemma reducible_fill `{!@LanguageCtx Λ K} e σ :
--     reducible (e, σ) → reducible (K e, σ).
--   Proof.
--     unfold reducible in *. intros [[] ?]. eexists; by apply fill_step.
--   Qed.

--   Lemma reducible_fill_inv `{!@LanguageCtx Λ K} e σ :
--     to_val e = None → reducible (K e, σ) → reducible (e, σ).
--   Proof.
--     intros ? [[e1 σ1] Hstep]; unfold reducible.
--     rewrite /step /= in Hstep.
--     rewrite fill_dmap // in Hstep.
--     apply dmap_pos in Hstep as ([e1' σ2] & ? & Hstep).
--     eauto.
--   Qed.
--   Lemma state_step_reducible e σ σ' α :
--     state_step σ α σ' > 0 → reducible (e, σ) ↔ reducible (e, σ').
--   Proof. apply state_step_not_stuck. Qed.
--   Lemma state_step_iterM_reducible e σ σ' α n:
--     iterM n (λ σ, state_step σ α) σ σ'> 0 → reducible (e, σ) ↔ reducible (e, σ').
--   Proof.
--     revert σ σ'.
--     induction n.
--     - intros σ σ'. rewrite iterM_O. by intros ->%dret_pos.
--     - intros σ σ'. rewrite iterM_Sn. rewrite dbind_pos. elim.
--       intros x [??]. pose proof state_step_reducible. naive_solver.
--   Qed.
--
--   Lemma irreducible_fill `{!@LanguageCtx Λ K} e σ :
--     to_val e = None → irreducible (e, σ) → irreducible (K e, σ).
--   Proof. rewrite -!not_reducible. naive_solver eauto using reducible_fill_inv. Qed.

--   Lemma irreducible_fill_inv `{!@LanguageCtx Λ K} e σ :
--     irreducible (K e, σ) → irreducible (e, σ).
--   Proof. rewrite -!not_reducible. naive_solver eauto using reducible_fill. Qed.
--
--   Lemma not_stuck_fill_inv K `{!@LanguageCtx Λ K} e σ :
--     not_stuck (K e, σ) → not_stuck (e, σ).
--   Proof.
--     rewrite /not_stuck /is_final /to_final /= -!not_eq_None_Some.
--     intros [?|?].
--     - auto using fill_not_val.
--     - destruct (decide (to_val e = None)); eauto using reducible_fill_inv.
--   Qed.
--
--   Lemma stuck_fill `{!@LanguageCtx Λ K} e σ :
--     stuck (e, σ) → stuck (K e, σ).
--   Proof. rewrite -!not_not_stuck. eauto using not_stuck_fill_inv. Qed.
--
--   Record pure_step (e1 e2 : expr Λ)  := {
--     pure_step_safe σ1 : reducible (e1, σ1);
--     pure_step_det σ : prim_step e1 σ (e2, σ) = 1;
--   }.
--
--   Class PureExec (φ : Prop) (n : nat) (e1 e2 : expr Λ) :=
--     pure_exec : φ → relations.nsteps pure_step n e1 e2.
--
--   Lemma pure_step_ctx K `{!@LanguageCtx Λ K} e1 e2 :
--     pure_step e1 e2 → pure_step (K e1) (K e2).
--   Proof.
--     intros [Hred Hstep]. split.
--     - unfold reducible in *. intros σ1.
--       destruct (Hred σ1) as [[]].
--       eexists. by eapply fill_step.
--     - intros σ.
--       rewrite -fill_step_prob //.
--       eapply (to_final_None_1 (_, σ)).
--       by eapply reducible_not_final.
--   Qed.
--
--   Lemma pure_step_nsteps_ctx K `{!@LanguageCtx Λ K} n e1 e2 :
--     relations.nsteps pure_step n e1 e2 →
--     relations.nsteps pure_step n (K e1) (K e2).
--   Proof. eauto using nsteps_congruence, pure_step_ctx. Qed.
--
--   Lemma rtc_pure_step_ctx K `{!@LanguageCtx Λ K} e1 e2 :
--     rtc pure_step e1 e2 → rtc pure_step (K e1) (K e2).
--   Proof. eauto using rtc_congruence, pure_step_ctx. Qed.
--
--   (* We do not make this an instance because it is awfully general. *)
--   Lemma pure_exec_ctx K `{!@LanguageCtx Λ K} φ n e1 e2 :
--     PureExec φ n e1 e2 →
--     PureExec φ n (K e1) (K e2).
--   Proof. rewrite /PureExec; eauto using pure_step_nsteps_ctx. Qed.
--
--   Lemma PureExec_reducible σ1 φ n e1 e2 :
--     φ → PureExec φ (S n) e1 e2 → reducible (e1, σ1).
--   Proof. move => Hφ /(_ Hφ). inversion_clear 1. apply H. Qed.
--
--   Lemma PureExec_not_val `{Inhabited (language.state Λ)} φ n e1 e2 :
--     φ → PureExec φ (S n) e1 e2 → to_val e1 = None.
--   Proof.
--     intros Hφ Hex.
--     destruct (PureExec_reducible inhabitant _ _ _ _ Hφ Hex) => /=.
--     simpl in *.
--     by eapply val_stuck.
--   Qed.
--
--   (* This is a family of frequent assumptions for PureExec *)
--   Class IntoVal (e : expr Λ) (v : val Λ) :=
--     into_val : of_val v = e.
--
--   Class AsVal (e : expr Λ) := as_val : ∃ v, of_val v = e.
--   (* There is no instance [IntoVal → AsVal] as often one can solve [AsVal] more *)
--   (* efficiently since no witness has to be computed. *)
--   Global Instance as_vals_of_val vs : TCForall AsVal (of_val <$> vs).
--   Proof.
--     apply TCForall_Forall, Forall_fmap, Forall_true=> v.
--     rewrite /AsVal /=; eauto.
--   Qed.
--
--   Lemma as_val_is_Some e :
--     (∃ v, of_val v = e) → is_Some (to_val e).
--   Proof. intros [v <-]. rewrite to_of_val. eauto. Qed.
--
--   Lemma fill_is_val e K `{@LanguageCtx Λ K} :
--     is_Some (to_val (K e)) → is_Some (to_val e).
--   Proof. rewrite -!not_eq_None_Some. eauto using fill_not_val. Qed.
--
--   Lemma rtc_pure_step_val `{!Inhabited (state Λ)} v e :
--     rtc pure_step (of_val v) e → to_val e = Some v.
--   Proof.
--     intros ?; rewrite <- to_of_val.
--     f_equal; symmetry; eapply rtc_nf; first done.
--     intros [e' [Hstep _]].
--     specialize (Hstep inhabitant) as [? Hval%val_stuck].
--     by rewrite to_of_val in Hval.
--   Qed.
-- End language.
